### ISSUE TITLE
Missing option.txt in beta driver

### ISSUE THREAD

**Issue by fuomag9** [itsmikethetech/Virtual-Display-Driver#141]
https://github.com/itsmikethetech/Virtual-Display-Driver/releases/tag/23.12.2HDR does not contain the option.txt file inside the folder
![image](https://github.com/user-attachments/assets/1ffa9a0e-5dbe-48dc-a147-fcd848669602)

**Comment by zjoasan** [comment]
in the beta, vdd_settings.xml have replaced  the options.txt, if you still want to base it on options.txt you can put your old options.txt into the folder and rename vdd_settings.xml. The driver will then look for options.txt and adapter.txt if adapter.txt isn't found it will go woth the gpu with most dedicated videoram. And in worst case scenario, it will ahve a few "sane" default resolutions.

**Comment by zjoasan** [comment]
> _it's best to have the "readme" updated to avoid confusion_
I personally feel more confident with documentation that changes with release version, there are often stuff in betas that never makes it to the release.

**Comment by fuomag9** [comment]
> > it's best to have the "readme" updated to avoid confusion
> 
> I personally feel more confident with documentation that changes with release version, there are often stuff in betas that never makes it to the release.

Something that could be done instead is to document installation for betas, so there's better testing if users know how to install it!

**Comment by zjoasan** [comment]
That is true, it could be done. But since we are a small team and we all have life outside of VDD,  Function comes and bug fixes come before user-documentation. It's an open source project, with a discord server, where we gladly help someone interested in documenting or help develop the project. Time is just as limited to me as it is for you, and you have to prioritize. Anyway, if you are using a beta you are expected to know enough to figure things out, or at least know where to get a hold of the information you think is lacking.And since the beta is built to use options.txt if the provided vdd_settings.xml is missing. just the name vdd_settings.xml should give you a hint if your options.txt isn't used.

**Comment by sofmeright** [comment]
I have been commenting to any seeming related posts trying to get my solution out there. If you are annoyed with the XML files you can convert between xml or txt or just do it all in the GUI.

Virtual Display Driver: Wizard
A GUI tool for manipulation (Install / Uninstall / Reload / Configure) of Indirect Display Driver Sample (IddSample) implementations like the HDR capable [Virtual Display Driver from itsmikethetech](https://github.com/itsmikethetech/Virtual-Display-Driver) that works on Windows 10/11. This installer/configuration tool is intended to provide a more elegant solution in place of needing to edit configs or use Device Manger for driver installation.
https://github.com/sofmeright/VirtualDisplayDriver_Wizard/blob/main/README.md

![PPIT-IddSample_Wiz-SS_GUI_Advanced](https://github.com/user-attachments/assets/aa482a1a-5482-4f7d-8426-0da3ef4df6e6)

> > > it's best to have the "readme" updated to avoid confusion
> > 
> > 
> > I personally feel more confident with documentation that changes with release version, there are often stuff in betas that never makes it to the release.
> 
> Something that could be done instead is to document installation for betas, so there's better testing if users know how to install it!

**Comment by itsmikethetech** [comment]
Updated readme and relevant questions answered.
