### ISSUE TITLE
[Bug]: LoadLibrary failed with error 87: The parameter is incorrect

### ISSUE THREAD

**Issue by NebulanSpaces** [itsmikethetech/Virtual-Display-Driver#191]
### Which OS?

Win10 Pro

### Which release?

22H2

### Describe the bug

When attempting to launch the modded version of Stardew Valley, it crashes giving me the error, "LoadLibrary failed with error 87: The parameter is incorrect."

### Expected behavior

- Launch SMAPI (Stardew Modding API)
- Loads Mods
- Launches Modded Game

**Comment by NebulanSpaces** [comment]
> uh, and does it work with a real screen ?

Yes, it did before I installed it

**Comment by bud3699** [comment]
If i were to take a guess, its stardew valley attempting to attach to the virtual display driver as a GPU. Try going to 

Settings > Display > Graphics and click browse and select the Stardew valley exe and click options and tell it to use specific GPU and try setting your GPU to the specific GPU, there isn't much we can do about this, since its the games fault

**Comment by NebulanSpaces** [comment]
That unfourtunately didn't work, I'll try to figure something out.

**Comment by bud3699** [comment]
Sorry about that, You might be able to get away with running it with compatibility mode. But other than that, stardew valley support is the only thing you can do about it.
